config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :subs, only: [:index, :new, :create, :show, :update, :edit]
  resources :posts, only: [:new, :create, :show, :update, :edit]
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :user_id, presence: true

  has_many :post_subs, inverse_of: :post
  has_many :subs, through: :post_subs

  belongs_to :author,
  class_name: "User"

end

app/models/post_sub.rb
class PostSub < ActiveRecord::Base
  validates :sub, :post, presence: true
  validates :post_id, uniqueness: {scope: :sub_id}

  belongs_to :post
  belongs_to :sub

end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :user_id, :description, :title, presence: true
  validates :title, uniqueness: true

  has_many :posts, through: :post_subs
  has_many :post_subs, inverse_of: :sub

  belongs_to :moderator,
  class_name: "User"

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :username, uniqueness: true

  has_many :subs
  has_many :posts

  attr_reader :password

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, pw)
    user = User.find_by(:username => username)
    user.is_password?(pw) ? user : nil
  end

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(:session_token => session[:session_token])
  end

  def log_in_user(user)
    session[:session_token] = user.session_token #reset_session_token
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_log_in!
    unless current_user
      redirect_to new_session_url
    end
  end

  def ensure_is_author!(post)
    if current_user.id == post.author_id
      true
    else
      false
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
    render :new
  end

  def create
    post = Post.new(post_params)
    post.user_id = current_user.id
    if post.save
      redirect_to post_url(post)
    else
      flash[:messages] = post.errors.full_messages
      redirect_to new_post_url
    end
  end

  def show
    @post = Post.find_by(:id => params[:id])
    render :show
  end

  def update
    post = Post.find_by(id: params[:id])
    if current_user.id == post.user_id
      if post.update(post_params)
        redirect_to post_url(post)
      else
        flash[:messages] = post.errors.full_messages
        redirect_to new_post_url
      end
    else
      flash[:messages] = ['You are not the author of this post!']
      redirect_to post_url(post)
    end
  end

  def edit
    @post = Post.find_by(:id => params[:id])
    if current_user.id == @post.user_id
      render :edit
    else
      flash[:messages] = ['You are not the author of this post!']
      redirect_to post_url(@post)
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(session_params[:username], session_params[:password])
    if user
      log_in_user(user)
      redirect_to user_url(user)
    else
      flash[:messages] = user.errors.full_messages
      redirect_to new_session_url
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end

  private
  def session_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  def index
    @subs = Sub.all
    render :index
  end

  def new
    @my_sub = Sub.new
    render :new
  end

  def create
    my_sub = Sub.new(sub_params)
    my_sub.user_id = current_user.id
    if my_sub.save
      redirect_to sub_url(my_sub)
    else
      flash[:messages] = my_sub.errors.full_messages
      redirect_to new_sub_url
    end
  end

  def show
    @my_sub = Sub.find_by(:id => params[:id])
    render :show
  end

  def update
    my_sub = Sub.find_by(id: params[:id])
    if my_sub.update(sub_params)
      redirect_to sub_url(my_sub)
    else
      flash[:messages] = my_sub.errors.full_messages
      redirect_to new_sub_url
    end
  end

  def edit
    @my_sub = Sub.find_by(:id => params[:id])
    render :edit
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.new(user_params)
    if user.save
      #log in user
      flash[:messages] = ["Successful log in"]
      redirect_to user_url(user)
    else
      flash.now[:messages] = user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  private 
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyReddit</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <ul>
<% if current_user %>
<li><%= "Logged in as #{current_user.username}" %></li>
<li><%= link_to "Create a sub!", new_sub_url %></li>
<li><%= link_to "All Subs", subs_url %></li>
<%=button_to "Logout", session_url, method: :delete%>
<% end %>
  </ul>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<% action_url = action=='edit' ? post_url(post) : posts_url %>
<% http_method = action=='edit' ? "PATCH" : "POST"  %>
<% submit_button = action=='edit' ? 'Edit post' : 'New post' %>

<form action=" <%= action_url %> " method="post">
  <input type="hidden" name="authenticity_token" value=" <%=form_authenticity_token%>">
  <input type="hidden" name="_method" value="<%=http_method%>">

  <label>Title
    <input type="text" name="post[title]" value="<%=post.title%>">
  </label>
  <br>
  <br>
  <label>Url
    <input type="text" name="post[url]" value="<%=post.url%>">
  </label>
  <br>
  <br>
  <label>Content
  <textarea name="post[content]" rows="8" cols="80"><%=post.content%></textarea>
  </label>
  <br>
  <br>

  <% Sub.all.each do |s| %>

  <label>
    <input type="checkbox"
    name="post[sub_ids][]"
    value="<%= s.id %>"
    <%= "checked" if post.sub_ids.include?(s.id) %> >
  <%= s.title %></label>
  <br>
  <% end %>

  <input type="submit" name="<%submit_button%>">

</form>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form", :post => @post, action: 'edit' %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form", :post => @post, action: 'new' %>

app/views/posts/show.html.erb
<h1><%=@post.title%></h1>

<h3>Content</h3>

<%=@post.content%>
<br>
<br>
<%= link_to 'Make new post!', new_post_url %>
<br>
<br>
<% if current_user.id == @post.user_id %>
  <%= button_to 'Edit', edit_post_url(@post), method: 'get' %>
<% end %>

app/views/subs/_form.html.erb
<% action_url = action=='edit' ? sub_url(my_sub) : subs_url %>
<% http_method = action=='edit' ? "PATCH" : "POST"  %>
<% submit_button = action=='edit' ? 'Edit sub' : 'New sub' %>

<form action=" <%= action_url %> " method="post">
  <input type="hidden" name="authenticity_token" value=" <%=form_authenticity_token%>">
  <input type="hidden" name="_method" value=" <%= http_method %> ">

  <label>Title
    <input type="text" name="sub[title]" value="<%= my_sub.title %>">
  </label>
  <br>
  <br>
  <label>Description
  <textarea name="sub[description]" rows="8" cols="80"><%=my_sub.description%></textarea>
  </label>
  <br>
  <br>

  <input type="submit" name="<%submit_button%>">

</form>

app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<%= render "form", :my_sub => @my_sub, action: 'edit' %>

app/views/subs/index.html.erb
<h1>All of my Subs</h1>
<ul>
<% @subs.each do |s| %>
<li><%= link_to "#{s.title}", sub_url(s) %></li>
<% end %>
</ul>

app/views/subs/new.html.erb
<h1>New Sub</h1>

<%= render "form", :my_sub => @my_sub, action: 'new'  %>

app/views/subs/show.html.erb
<h1> <%= @my_sub.title %> </h1>

<h3>Description</h3>

<%= @my_sub.description %>
<br>
<br>
<%= link_to 'Make new post!', new_post_url %>
<br>
<br>
<ul>
<% @my_sub.posts.each do |post| %>
<li><%= link_to "#{post.title}", post_url(post) %></li>
<% end %>
</ul>
<% if current_user.id == @my_sub.user_id %>
  <%= button_to 'Edit', edit_sub_url(@my_sub), method: 'get' %>
<% end %>

app/views/users/new.html.erb
<h1>New user</h1>
<%= link_to 'Sign in!', new_session_url %>
<br>
<br>
<form action=" <%= users_url %> " method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label>Username
    <input type="text" name="user[username]">
  </label>
  <br>
  <br>
  <label>Password
    <input type="password" name="user[password]">
  </label>
  <br>
  <br>
  <input type="submit" value="Add user">
</form>

app/views/users/show.html.erb
<h1>Hi there</h1>